# Generated by Django 3.2.4 on 2021-06-30 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('film_name', models.CharField(help_text='255 characters or fever', max_length=255, verbose_name='a name title')),
                ('film_description', models.CharField(max_length=1000, null=True)),
                ('image', models.ImageField(null=True, upload_to='static/media/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(help_text='letters, hyphens, numbers and underscores', max_length=255)),
                ('category', models.ForeignKey(db_column='category', null=True, on_delete=django.db.models.deletion.PROTECT, to='film.category')),
            ],
        ),
    ]
