# Generated by Django 3.2.4 on 2021-07-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall',
            field=models.CharField(max_length=100, verbose_name='hall'),
        ),
    ]
