# Generated by Django 3.2.4 on 2021-07-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(null=True, upload_to='static/media/'),
        ),
    ]
