# Generated by Django 3.2.4 on 2021-07-05 12:44

from django.db import migrations, models
import films.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, validators=[films.validators.positive_validator]),
        ),
    ]
