# Generated by Django 3.2.4 on 2021-07-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pid',
            new_name='id',
        ),
    ]
