# Generated by Django 3.2.4 on 2021-07-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_pid_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='pid',
        ),
    ]
